Учебный проект: холст
htmlacademy-javascript/1466459-code-and-magick-21 pull request #2
Opened 2020-10-09 14:55 UTC by andreysereda1976

2020-10-09 16:59 UTC, maxim-usikov requested changes

2020-10-09 16:59 UTC, maxim-usikov commented on js/stat.js
> +  let saturation = Math.random() * 100;
Давай напишем функцию `getRandomInt(min, max)` которая возвращает целое число в пределе: `[min, max)`

* min включительно
* max не включительно

2020-10-09 16:59 UTC, maxim-usikov commented on js/stat.js
> +  ctx.fillText(`Список результатов:`, START_X, 60);
Для отрисовки текста, давай сделаем отдельную функцию: `renderText(...)` - по примеру функции `renderRectangle`

2020-10-09 16:59 UTC, maxim-usikov commented on js/stat.js
> +  let barColor = `rgba(255, 0, 0, 1)`;
Если переменная далее нигде не меняется, мы не присваиваем в нее новое значение - следует использовать ключевое слово `const variableName = ...`

2020-10-09 18:14 UTC, andreysereda1976 commented on js/stat.js
> +  let barColor = `rgba(255, 0, 0, 1)`;
так они же все могут меняться дальше внутри цикла. или maximumTime не считается за изменение,  что она каждый раз пересчитывается при перезапуске ctx?

2020-10-12 18:50 UTC, maxim-usikov approved these changes

2020-10-12 18:51 UTC, merged